# Generated by Django 4.1.5 on 2023-01-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=100, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executor', to='tasks.employee', verbose_name='Исполнитель задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(max_length=100, verbose_name='Название задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reporter', to='tasks.employee', verbose_name='Автор задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_status',
            field=models.CharField(default='Created', max_length=50, verbose_name='Статус'),
        ),
    ]
