# Generated by Django 4.1.5 on 2023-01-24 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_employee_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reporter', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
